version: 0.2
run-as: root

phases:

  install:
    commands:
      - echo Downloading the Hadolint tool...
      - wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
      - cp hadolint /bin
      - chmod +x /bin/hadolint
      - /bin/hadolint --version
      - echo Installing Checkov:static code analysis tool for scanning infrastructure as code files for misconfigurations...!! 
      - curl https://bootstrap.pypa.io/get-pip.py | python3
      - pip3 install checkov
      - checkov --version 

  pre_build:
    commands:
      - echo Running Hadolint and Checkov tools on the Dockerfile
  build:
    commands:
      - echo Build started on `date`
      - echo Validating the Dockerfile using Hadolint tool...
      - /bin/hadolint Dockerfile
      - echo Using Checkov tool for scanning the Dockerfile...
      - checkov -f Dockerfile
      - checkov -d . -o json 
      - checkov -d . -o json > checkov.json
      - cat checkov.json
      - apt-get update -y && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
      - aws s3 cp checkov.json s3://sasttestgokul-bucket/SCA-$CODEBUILD_RESOLVED_SOURCE_VERSION.json
  post_build:
    commands:
      - echo Build completed on `date`
